apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demosecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demosecret
    kind: SecretStore
  target:
    name: demosecret
    creationPolicy: Owner
  data:
  - secretKey: demosecret-key
    remoteRef:
      key: test/runtime/my_super_secret
  - secretKey: demosecret-key2
    remoteRef:
      key: test/runtime/my_super_secret2
