apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: awscli
  name: awscli
spec:
  containers:
  - image: amazon/aws-cli
    name: awscli
    command: ["/bin/bash", "-c", "sleep 60000"] 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
